### PR TITLE
Update base to 4.15.1.0

### PR DESCRIPTION
**Pull request by willbasky**
I updated base version, bit it missed after merged. Once again.

### CODE REVIEW

**Comment by aravind-mohandas** [comment]
Sorry about that, for some reason base was running on an older version on my system, I modified the .cabal file for testing, and forgot to change it back.

**Comment by aravind-mohandas** [comment]
Hi @willbasky, what version of ghc and cabal are you using? I was having trouble getting konnakol to build (I'm using windows)

**Comment by willbasky** [comment]
image

**Comment by aravind-mohandas** [comment]
Ah, alright. I couldn't get it to build using ghc-9.4.1, which is required for tidal-1.9.0.

**Comment by willbasky** [comment]
see, I use ghc-9.0.2, highlighted by blue

**Pull request merged**
